name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello from actions" 