name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello from actions"
      - run: npm i
      - run: eslint src/**/*.ts src/**/*.tsx
      - run: npm run lint
