name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types: [opened, reopened]
jobs:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Hello, from github Actions..."
